'use client';

import Link from 'next/link';
import { useLanguage } from '@/contexts/LanguageContext';
import SiteFooter from '@/components/SiteFooter';
import LanguageSwitcher from '@/components/LanguageSwitcher';

const UPDATED = 'April 2026';
const UPDATED_IT = 'Aprile 2026';

export default function DisclaimerPage() {
  const { locale } = useLanguage();
  const it = locale === 'it';

  const sections = it ? [
    {
      title: 'Programma di Affiliazione Amazon',
      body: `ReviewSnap è un partecipante al Programma di Affiliazione Amazon EU, un programma pubblicitario che consente ai siti di percepire una commissione pubblicitaria mediante la pubblicità e la creazione di link verso Amazon.it.\n\nQuando fai clic su un link di prodotto su ReviewSnap e acquisti il prodotto su Amazon, potremmo ricevere una piccola commissione senza alcun costo aggiuntivo per te. Le commissioni ci aiutano a mantenere il sito gratuito.`,
    },
    {
      title: 'Indipendenza delle analisi',
      body: `Le commissioni di affiliazione non influenzano mai i verdetti, i punteggi o le analisi generati dall'IA. Nessun brand paga per ricevere una recensione positiva. Tutti i verdetti sono generati automaticamente da Claude AI sulla base delle recensioni pubbliche dei clienti Amazon.`,
    },
    {
      title: 'Accuratezza delle informazioni',
      body: `Le analisi di ReviewSnap sono generate da intelligenza artificiale e si basano su recensioni di clienti reali raccolte pubblicamente da Amazon. Non garantiamo l'accuratezza, la completezza o l'attualità delle informazioni fornite.\n\nPrezzi, disponibilità e caratteristiche dei prodotti possono variare. Prima di effettuare un acquisto, ti consigliamo di verificare le informazioni direttamente su Amazon.`,
    },
    {
      title: 'Non siamo consulenti',
      body: `Le informazioni presenti su ReviewSnap hanno finalità puramente informative e non costituiscono consulenza professionale d'acquisto. L'utente è l'unico responsabile delle proprie decisioni d'acquisto.`,
    },
    {
      title: 'Marchi registrati',
      body: `Amazon, Amazon.it e il logo Amazon sono marchi registrati di Amazon.com, Inc. o delle sue affiliate. ReviewSnap non è affiliato, sponsorizzato o approvato da Amazon.`,
    },
  ] : [
    {
      title: 'Amazon Affiliate Disclosure',
      body: `ReviewSnap is a participant in the Amazon Services LLC Associates Program, an affiliate advertising program designed to provide a means for sites to earn advertising fees by advertising and linking to Amazon.com and affiliated sites.\n\nWhen you click a product link on ReviewSnap and purchase the product on Amazon, we may receive a small commission at no extra cost to you. These commissions help us keep the service free.`,
    },
    {
      title: 'Analysis Independence',
      body: `Affiliate commissions never influence the verdicts, scores, or analyses generated by AI. No brand pays for a positive review. All verdicts are generated automatically by Claude AI based on public Amazon customer reviews.`,
    },
    {
      title: 'Accuracy of Information',
      body: `ReviewSnap analyses are AI-generated and based on real customer reviews publicly available on Amazon. We do not guarantee the accuracy, completeness, or timeliness of the information provided.\n\nProduct prices, availability, and features may change. We recommend verifying information directly on Amazon before making a purchase.`,
    },
    {
      title: 'Not Professional Advice',
      body: `Information on ReviewSnap is for informational purposes only and does not constitute professional purchasing advice. You are solely responsible for your own purchasing decisions.`,
    },
    {
      title: 'Trademarks',
      body: `Amazon, Amazon.com, and the Amazon logo are trademarks of Amazon.com, Inc. or its affiliates. ReviewSnap is not affiliated with, sponsored by, or endorsed by Amazon.`,
    },
  ];

  return (
    <div className="min-h-screen bg-[#f7f8fa] flex flex-col">
      <header className="bg-[#131921] py-3 px-4 sticky top-0 z-50">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-md bg-[#FF9900] flex items-center justify-center">
              <svg className="w-4 h-4 text-[#131921]" viewBox="0 0 24 24" fill="currentColor">
                <path d="M12 2l2.4 7.4H22l-6.2 4.5 2.4 7.4L12 17l-6.2 4.3 2.4-7.4L2 9.4h7.6L12 2z" />
              </svg>
            </div>
            <span className="text-white font-bold text-lg tracking-tight">ReviewSnap</span>
          </Link>
          <LanguageSwitcher />
        </div>
      </header>
      <div className="h-[3px] bg-[#FF9900]" />

      <main className="flex-1 max-w-2xl mx-auto w-full px-4 py-10 space-y-6">
        <div>
          <h1 className="text-3xl font-bold text-[#0f1111]">Disclaimer</h1>
          <p className="text-xs text-[#565959] mt-1">
            {it ? `Ultimo aggiornamento: ${UPDATED_IT}` : `Last updated: ${UPDATED}`}
          </p>
        </div>

        {sections.map(s => (
          <div key={s.title} className="card p-6 space-y-2">
            <h2 className="font-bold text-[#0f1111] text-sm">{s.title}</h2>
            {s.body.split('\n').map((line, i) => (
              <p key={i} className="text-sm text-[#333] leading-relaxed">{line}</p>
            ))}
          </div>
        ))}
      </main>

      <SiteFooter />
    </div>
  );
}
